spring:
  jpa:
    hibernate:
      ddl-auto: validate
    # This helps Hibernate wait for Flyway
    properties:
      hibernate:
        default_schema: public
  flyway:
    enabled: true
    baseline-on-migrate: true
    # Tells Flyway where your V1__init.sql is
    locations: classpath:db/migration
  data:
    redis:
      host: localhost
      port: 6379

auth:
  jwt:
    secret: "bGF0ZXNhbGVzaW5nbW9yZWNhcmVmdWxseXRyaWFuZ2xlZXF1aXBtZW50eW91dGhza2k"
    access-token-expiry: 3600000      # 1 hour in ms
    refresh-token-expiry: 2592000000  # 30 days in ms
