openapi: 3.0.3
info:
  title: User API
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /auth/login:
    post:
      summary: log in user
      operationId: login
      tags:
        - Authentication
      requestBody:
        description: Username And Password
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        '401':
          description: Invalid email or password

  /auth/refresh:
    post:
      summary: Refresh Token
      operationId: refresh
      tags:
        - Authentication
      requestBody:
        description: Employee data to save
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        '401':
          description: Refresh token invalid or expired

  /auth/logout:
    post:
      tags:
        - Authentication
      summary: Logout and revoke tokens
      operationId: logout
      responses:
        '204':
          description: Successfully logged out
        '401':
          description: Invalid or missing token

components:
  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    RefreshRequest:
      type: object
      properties:
        refreshToken:
          type: string

    LoginResponse:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
        email:
          type: string
        roles:
          type: array
          items:
            type: string

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string